apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: helloworld
        image: https://jimacr1.azurecr.io/helloworld
        ports:
        - containerPort: 5000
          name: helloworld

