apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapi
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: jimacr1.azurecr.io/helloworld:latest
        ports:
        - containerPort: 5000
